config/routes.rb
Jt2012::Application.routes.draw do

  match "login(/:message)" => "login#index", :as => "login"
  match "auth" => "login#auth", :as => "auth"
  match "logout" => "login#logout", :as => "logout"

  match "change_lang/:lang" => "main#change_lang", :as => "change_lang"
  match "index" => "main#index", :as => "init"
  match "about" => "main#about", :as => "about"
  match "lux" => "main#lux", :as => "lux"
  match "contact" => "main#contact", :as => "contact"

  match "posts" => "blogs#index"
  match "post/:id" => "blogs#show"

  resources :admins
  resources :contacts
  resources :blogs

  root :to => 'main#index'

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <br />
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :email %>
  </div>

<% if @pass %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<div class="cborder centered main_item white_background">
  <div class="internal">
    <div class="title">
      Edit Admin
    </div>

    <div>
    	<%= render 'form' %>
    </div>
  </div>
</div>

<div class="centered main_item">
  <%= link_to 'Back', admins_path, :class => "white_link" %>
</div>

app/views/admins/index.html.erb
<div class="cborder centered main_item white_background">
  <div class="internal">
    <div class="title">
      Admins
    </div>

    <div>
      <table>
        <tr>
          <th>User</th>
          <th></th>
          <th></th>
        </tr>

      <% @admins.each do |admin| %>
        <tr>
          <td><%= admin.email %></td>
          <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
          <% if admin.id != 1 %>
            <td><%= link_to 'Remove', admin, confirm: 'Are you sure you want to remove this admin?', method: :delete %></td>
          <% else %>
            <td></td>
          <% end %>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

<div class="centered main_item">
  <%= link_to 'New Admin', new_admin_path, :class => "white_link" %>
</div>

app/views/admins/new.html.erb
<div class="cborder centered main_item white_background">
  <div class="internal">
    <div class="title">
      New Admin
    </div>

    <div>
    	<%= render 'form' %>
    </div>
  </div>
</div>

<div class="centered main_item">
  <%= link_to 'Back', admins_path, :class => "white_link" %>
</div>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @admin.email %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>